### ISSUE TITLE
How to create APK?

### ISSUE THREAD

**Issue by anonyvietofficial** [jxroot/adbwebkit#1]
i don't see how to create apk to install to victim's device?

**Comment by jxroot** [comment]
> i don't see how to create apk to install to victim's device?

create apk can you explain?
you can install apk on application tab see this [video](https://security.tosinso.com/fa/videos/11621/%D9%85%D8%B9%D8%B1%D9%81%DB%8C-%D8%A7%D8%A8%D8%B2%D8%A7%D8%B1-ADB-WEBKiT)

**Comment by anonyvietofficial** [comment]
sorry, but how to connect adbwebkit to device or bluestack?
i think must install apk to android, you can connect adbwebkit ?

**Comment by jxroot** [comment]
💿 Installation And Usage
1- Enable Usb Debugging On Android Device

2- Connect To Android Device

3- Add ADB To Environment

git clone https://github.com/jxroot/adbwebkit.git
cd adbwebkit
php -S 127.0.0.1:8000

After Do this open cmd type adb devices you can see device label 
bluestacks Default 127.0.0.1:5555

**Comment by jxroot** [comment]
> sorry, but how to connect adbwebkit to device or bluestack?
> i think must install apk to android, you can connect adbwebkit ?

💿 Installation And Usage
1- Enable Usb Debugging On Android Device

2- Connect To Android Device

3- Add ADB To Environment

git clone https://github.com/jxroot/adbwebkit.git
cd adbwebkit
php -S 127.0.0.1:8000

After Do this open cmd type adb devices you can see device label
bluestacks Default 127.0.0.1:5555
use plus float button to add device

**Comment by anonyvietofficial** [comment]
i can Enable Usb Debugging On Android Device, but i don't understand Step 2,3
Can you create video tut?
