### ISSUE TITLE
Termux Installation Error

### ISSUE THREAD

**Issue by Alexmuench15** [jxroot/adbwebkit#10]
![Screenshot_20220526-161328_Termux](https://user-images.githubusercontent.com/104004386/170506007-a77f6a5c-5b40-49cc-b956-a204310273c2.jpg)

Downloading tbe adbwebkit.sh file worked, chmodding it aswell, I also checked with ls that it really worked but the bash part has its problems.

Error code:
adbwebkit.sh: line 1: syntax error near unexpected token `<'
adbwebkit.sh: line 1: `<html><head><title>Object moved</title></'ead><body>

Thanks for help in advance :)

**Comment by jxroot** [comment]
i fix it test 
copy and run in termux

curl -o adbwebkit.sh https://pastebin.pl/view/raw/f57a60c7 && chmod +x adbwebkit.sh  && bash adbwebkit.sh

**Comment by Alexmuench15** [comment]
Thanks Installation worked now.
How do I connect to target device?
Sadly your Youtube Tutorial got taken down, so I'm struggling how and what to do :/

**Comment by jxroot** [comment]
> Thanks Installation worked now. How do I connect to target device? Sadly your Youtube Tutorial got taken down, so I'm struggling how and what to do :/

watch this [video](https://s20.picofile.com/file/8443177584/adbfull.mp4.html)
And if you can not solve the problem, send me a message on Instagram [sectoolfa](https://www.instagram.com/sectoolfa/)
