### ISSUE TITLE
Error php

### ISSUE THREAD

**Issue by Jeiel17** [jxroot/adbwebkit#11]
ERROR:
Warning: Undefined variable $verb in

![Screenshot_20220620-210910-175.png](https://user-images.githubusercontent.com/72875404/174691168-c4ce5aee-7a5b-40ea-b5a2-0595d09c5287.png)

**Comment by jxroot** [comment]
> ERROR: Warning: Undefined variable $verb in
> 
> ![Screenshot_20220620-210910-175.png](https://user-images.githubusercontent.com/72875404/174691168-c4ce5aee-7a5b-40ea-b5a2-0595d09c5287.png)

Hello dear friend, the adb connection is not working properly, you have to establish this connection manually

watch this [video](https://s20.picofile.com/file/8443177584/adbfull.mp4.html)
And if you can not solve the problem, send me a message on Instagram [sectoolfa](https://www.instagram.com/sectoolfa/)
