### ISSUE TITLE
Request php not working 

### ISSUE THREAD

**Issue by Max000110** [jxroot/adbwebkit#14]
![Screenshot_2024_0128_013752](https://github.com/jxroot/adbwebkit/assets/153953374/19352796-2fe9-45c8-8ee0-119fbf723195)
 Plzz fix this or give me solution.

**Comment by jxroot** [comment]
hey dude  its about php version some function Deprecated use older version 

> ![Screenshot_2024_0128_013752](https://private-user-images.githubusercontent.com/153953374/300213117-19352796-2fe9-45c8-8ee0-119fbf723195.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Mjk4NTcsIm5iZiI6MTcwNjcyOTU1NywicGF0aCI6Ii8xNTM5NTMzNzQvMzAwMjEzMTE3LTE5MzUyNzk2LTJmZTktNDVjOC04ZWUwLTExOWZiZjcyMzE5NS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxOTMyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTkzMDAyNDBjZGNkZjZlMjM4NmRkOWNiODVlYjZlMjdiOWZmNTgwMTViOGE2YTJmNjIwYjBhNTYzMDRlYjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gCDKuSGoQz8kxFruPFEvGo_3RaLreE_I6yUCoCmDlvE) Plzz fix this or give me solution.

hey dude  its about php version some function Deprecated use older version
