### ISSUE TITLE
cant add device in adb webkit

### ISSUE THREAD

**Issue by GitHub0liver** [jxroot/adbwebkit#4]
![Unavngivet](https://user-images.githubusercontent.com/92673943/137919727-3a4187df-5cb4-4df0-a660-9028c486e093.png)

**Comment by jxroot** [comment]
add device with adb custome command

**Comment by makarhuyaker** [comment]
same problem

**Comment by jxroot** [comment]
> same problem

Guys, I think you are going the wrong way at all
You need to connect to your device manually first and then add it to the web environment. If there is no device to display, a manual address must be given.
