### ISSUE TITLE
not working....

### ISSUE THREAD

**Issue by XKMR** [jxroot/adbwebkit#6]
I done the configs and nothing works. for example shell says "ERROR" after any command. 
or screenshots does not do anything.

I suppose these errors are not meant to be there.

(PHP CMD):

[Tue Mar 29 18:44:46 2022] ::1:19977 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory
[Tue Mar 29 18:44:47 2022] ::1:19978 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory
[Tue Mar 29 18:44:50 2022] ::1:19979 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory
[Tue Mar 29 18:44:52 2022] ::1:19980 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory

I think in request.php, this part of your code is not working/running:

![image](https://user-images.githubusercontent.com/58393719/160646316-3748ba0e-9330-4e60-9833-f18dc94bdaac.png)

and also, im iranian :)

**Comment by jxroot** [comment]
> I done the configs and nothing works. for example shell says "ERROR" after any command. or screenshots does not do anything.
> 
> I suppose these errors are not meant to be there.
> 
> (PHP CMD):
> 
> [Tue Mar 29 18:44:46 2022] ::1:19977 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory [Tue Mar 29 18:44:47 2022] ::1:19978 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory [Tue Mar 29 18:44:50 2022] ::1:19979 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory [Tue Mar 29 18:44:52 2022] ::1:19980 [404]: /ERRORusers//screenshot/.4156.png - No such file or directory
> 
> I think in request.php, this part of your code is not working/running:
> 
> ![image](https://user-images.githubusercontent.com/58393719/160646316-3748ba0e-9330-4e60-9833-f18dc94bdaac.png)
> 
> and also, im iranian :)




Hello dear friend, the adb connection is not working properly, you have to establish this connection manually

watch this [video](https://s20.picofile.com/file/8443177584/adbfull.mp4.html)
And if you can not solve the problem, send me a message on Instagram [sectoolfa](https://www.instagram.com/sectoolfa/)

**Comment by XKMR** [comment]
Thanks.very helpful
